services:
  db:
    image: postgres:15
    env_file:
    - backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  django:
    build:
      target: dev
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
    - backend/.env
    volumes:
      - ./backend:/app 

volumes:
  postgres_data: