# Generated by Django 5.2.7 on 2026-02-08 10:38

import backend.storage_backends
import django.core.validators
import django.db.models.deletion
import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_created_at_game_updated_at_gamerules"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "image")],
                        default="image",
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        storage=backend.storage_backends.PrivateMediaStorage(),
                        upload_to=media.models.file_upload_to_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpeg", "jpg"]
                            )
                        ],
                    ),
                ),
                (
                    "file_location",
                    models.CharField(
                        choices=[("games_img", "games_img")],
                        default="games_img",
                        editable=False,
                        max_length=255,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
