# Generated by Django 5.2.7 on 2026-02-01 12:49

import backend.storage_backends
import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_location",
                    models.CharField(
                        choices=[("games_img", "games_img")], max_length=255
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        choices=[("png", "png"), ("jpg", "jpg"), ("jpeg", "jpeg")],
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "image")],
                        default="image",
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        storage=backend.storage_backends.PrivateMediaStorage(),
                        upload_to=media.models.file_upload_to_path,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
