# Generated by Django 5.2.7 on 2026-02-05 19:54

import backend.storage_backends
import django.core.validators
import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="extension",
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                storage=backend.storage_backends.PrivateMediaStorage(),
                upload_to=media.models.file_upload_to_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file_location",
            field=models.CharField(
                choices=[("games_img", "games_img")], editable=False, max_length=255
            ),
        ),
    ]
